<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DaftarSuratSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('daftar_surat')->insert([
            [
                'id'            => '1',
                'nama_surat'    => 'SURAT KETERANGAN USAHA',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '478',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => "surat-keterangan-usaha",
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '2',
                'nama_surat'    => 'SURAT KETERANGAN TEMPAT USAHA',
                'jenis_surat'   => 'internal',
                'kode_surat'    => '478',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => "surat-keterangan-tempat-usaha",
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '3',
                'nama_surat'    => 'SURAT KETERANGAN TIDAK MAMPU',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '460',
                'no_urut_surat' => '001',
                'penerbit'      => 'Kesra',
                'is_active'     => true,
                'url'           => "surat-keterangan-tidak-mampu",
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '4',
                'nama_surat'    => 'SURAT KETERANGAN KELUARGA MISKIN',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '460',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-keluarga-miskin',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '5',
                'nama_surat'    => 'SURAT KETERANGAN PENGHASILAN',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '460',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-penghasilan',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '6',
                'nama_surat'    => 'SURAT KETERANGAN BEPERGIAN',
                'jenis_surat'   => 'internal',
                'kode_surat'    => '478',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-bepergian',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '7',
                'nama_surat'    => 'SURAT KETERANGAN BEDA NAMA',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '141',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-beda-nama',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '8',
                'nama_surat'    => 'SURAT KUASA',
                'jenis_surat'   => 'internal',
                'kode_surat'    => null,
                'no_urut_surat' => null,
                'penerbit'      => null,
                'is_active'     => true,
                'url'           => 'surat-kuasa',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '9',
                'nama_surat'    => 'SURAT KETERANGAN PINDAH DATANG',
                'jenis_surat'   => 'internal',
                'kode_surat'    => '475',
                'no_urut_surat' => '001',
                'penerbit'      => 'PEM',
                'is_active'     => true,
                'url'           => 'surat-keterangan-pindah-datang',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '10',
                'nama_surat'    => 'SURAT KETERANGAN KEMATIAN',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '474.13',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-kematian',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '11',
                'nama_surat'    => 'SURAT KETERANGAN PENDAFTARAN HAJI',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '479.2',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-pendaftaran-haji',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '12',
                'nama_surat'    => 'SURAT KETERANGAN KELAHIRAN',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '474.1',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-kelahiran',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '13',
                'nama_surat'    => 'SURAT KETERANGAN DOMISILI',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '479',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-domisili',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '14',
                'nama_surat'    => 'SURAT KETERANGAN BUKAN PNS',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '141',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-bukan-pns',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '15',
                'nama_surat'    => 'SURAT KETERANGAN TANAH',
                'jenis_surat'   => 'internal',
                'kode_surat'    => '395.3',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-tanah',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '16',
                'nama_surat'    => 'SURAT KETERANGAN BELUM MENIKAH',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '470',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-belum-menikah',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '17',
                'nama_surat'    => 'SURAT KETERANGAN TIDAK MEMILIKI RUMAH',
                'jenis_surat'   => 'publik',
                'kode_surat'    => '141',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pem',
                'is_active'     => true,
                'url'           => 'surat-keterangan-tidak-memiliki-rumah',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '18',
                'nama_surat'    => 'SURAT KETERANGAN KEMATIAN LAMA',
                'jenis_surat'   => 'internal',
                'kode_surat'    => '474.13',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-kematian-lama',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '19',
                'nama_surat'    => 'SURAT KETERANGAN AHLI WARIS',
                'jenis_surat'   => 'internal',
                'kode_surat'    => '474.13',
                'no_urut_surat' => '001',
                'penerbit'      => 'Pel',
                'is_active'     => true,
                'url'           => 'surat-keterangan-ahli-waris',
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ]
        ]);
    }
}
