<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class RTSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rw1 = \DB::table("rws")->where("nomor", "001")->first();
        $rw2 = \DB::table("rws")->where("nomor", "002")->first();
        $rw3 = \DB::table("rws")->where("nomor", "003")->first();
        $rw4 = \DB::table("rws")->where("nomor", "004")->first();
        $rw5 = \DB::table("rws")->where("nomor", "005")->first();
        $rw6 = \DB::table("rws")->where("nomor", "006")->first();
        $rw7 = \DB::table("rws")->where("nomor", "007")->first();
        $rw8 = \DB::table("rws")->where("nomor", "008")->first();
        $rw9 = \DB::table("rws")->where("nomor", "009")->first();

        $cimara = \DB::table("dusuns")->where("id", 1)->first();
        $sukamulya = \DB::table("dusuns")->where("id", 2)->first();
        $awiluar = \DB::table("dusuns")->where("id", 3)->first();
        $purwasari = \DB::table("dusuns")->where("id", 4)->first();
        
        \DB::table('rts')->insert([
            [
                'id'                =>1,
                'nomor'             =>'001',
                'rw_id'             =>$rw1->id,
                'rw'                =>$rw1->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>2,
                'nomor'             =>'002',
                'rw_id'             =>$rw1->id,
                'rw'                =>$rw1->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>3,
                'nomor'             =>'003',
                'rw_id'             =>$rw1->id,
                'rw'                =>$rw1->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>4,
                'nomor'             =>'004',
                'rw_id'             =>$rw1->id,
                'rw'                =>$rw1->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>5,
                'nomor'             =>'001',
                'rw_id'             =>$rw2->id,
                'rw'                =>$rw2->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>6,
                'nomor'             =>'002',
                'rw_id'             =>$rw2->id,
                'rw'                =>$rw2->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>7,
                'nomor'             =>'003',
                'rw_id'             =>$rw2->id,
                'rw'                =>$rw2->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>8,
                'nomor'             =>'004',
                'rw_id'             =>$rw2->id,
                'rw'                =>$rw2->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>9,
                'nomor'             =>'005',
                'rw_id'             =>$rw2->id,
                'rw'                =>$rw2->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>10,
                'nomor'             =>'001',
                'rw_id'             =>$rw3->id,
                'rw'                =>$rw3->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>11,
                'nomor'             =>'002',
                'rw_id'             =>$rw3->id,
                'rw'                =>$rw3->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>12,
                'nomor'             =>'003',
                'rw_id'             =>$rw3->id,
                'rw'                =>$rw3->nomor,
                'dusun_id'          =>$cimara->id,
                'dusun'             =>$cimara->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>13,
                'nomor'             =>'001',
                'rw_id'             =>$rw4->id,
                'rw'                =>$rw4->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>14,
                'nomor'             =>'002',
                'rw_id'             =>$rw4->id,
                'rw'                =>$rw4->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>15,
                'nomor'             =>'003',
                'rw_id'             =>$rw4->id,
                'rw'                =>$rw4->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>16,
                'nomor'             =>'004',
                'rw_id'             =>$rw4->id,
                'rw'                =>$rw4->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>17,
                'nomor'             =>'005',
                'rw_id'             =>$rw4->id,
                'rw'                =>$rw4->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>18,
                'nomor'             =>'006',
                'rw_id'             =>$rw4->id,
                'rw'                =>$rw4->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>19,
                'nomor'             =>'001',
                'rw_id'             =>$rw5->id,
                'rw'                =>$rw5->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>20,
                'nomor'             =>'002',
                'rw_id'             =>$rw5->id,
                'rw'                =>$rw5->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>21,
                'nomor'             =>'003',
                'rw_id'             =>$rw5->id,
                'rw'                =>$rw5->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>22,
                'nomor'             =>'004',
                'rw_id'             =>$rw5->id,
                'rw'                =>$rw5->nomor,
                'dusun_id'          =>$sukamulya->id,
                'dusun'             =>$sukamulya->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>23,
                'nomor'             =>'001',
                'rw_id'             =>$rw6->id,
                'rw'                =>$rw6->nomor,
                'dusun_id'          =>$awiluar->id,
                'dusun'             =>$awiluar->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>24,
                'nomor'             =>'002',
                'rw_id'             =>$rw6->id,
                'rw'                =>$rw6->nomor,
                'dusun_id'          =>$awiluar->id,
                'dusun'             =>$awiluar->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>25,
                'nomor'             =>'003',
                'rw_id'             =>$rw6->id,
                'rw'                =>$rw6->nomor,
                'dusun_id'          =>$awiluar->id,
                'dusun'             =>$awiluar->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>26,
                'nomor'             =>'001',
                'rw_id'             =>$rw7->id,
                'rw'                =>$rw7->nomor,
                'dusun_id'          =>$awiluar->id,
                'dusun'             =>$awiluar->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>27,
                'nomor'             =>'002',
                'rw_id'             =>$rw7->id,
                'rw'                =>$rw7->nomor,
                'dusun_id'          =>$awiluar->id,
                'dusun'             =>$awiluar->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>28,
                'nomor'             =>'003',
                'rw_id'             =>$rw7->id,
                'rw'                =>$rw7->nomor,
                'dusun_id'          =>$awiluar->id,
                'dusun'             =>$awiluar->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>29,
                'nomor'             =>'001',
                'rw_id'             =>$rw8->id,
                'rw'                =>$rw8->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>30,
                'nomor'             =>'002',
                'rw_id'             =>$rw8->id,
                'rw'                =>$rw8->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>31,
                'nomor'             =>'003',
                'rw_id'             =>$rw8->id,
                'rw'                =>$rw8->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>32,
                'nomor'             =>'004',
                'rw_id'             =>$rw8->id,
                'rw'                =>$rw8->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>33,
                'nomor'             =>'005',
                'rw_id'             =>$rw8->id,
                'rw'                =>$rw8->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                =>34,
                'nomor'             =>'001',
                'rw_id'             =>$rw9->id,
                'rw'                =>$rw9->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                => 35,
                'nomor'             =>'002',
                'rw_id'             =>$rw9->id,
                'rw'                =>$rw9->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                => 36,
                'nomor'             =>'003',
                'rw_id'             =>$rw9->id,
                'rw'                =>$rw9->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
            [
                'id'                => 37,
                'nomor'             =>'004',
                'rw_id'             =>$rw9->id,
                'rw'                =>$rw9->nomor,
                'dusun_id'          =>$purwasari->id,
                'dusun'             =>$purwasari->nama_dusun,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],
        ]);
    }
}
